# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# test 2
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '12.x'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: docker push
      run: |
       ${{ secrets.DOCKER_LOGIN }}
       docker build -t docker.pkg.github.com/erjiangao/tutor-selection-tool-vue/tutor-selection-tool-vue:latest .
       docker push docker.pkg.github.com/erjiangao/tutor-selection-tool-vue/tutor-selection-tool-vue:latest
        
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          ${{ secrets.DOCKER_LOGIN }}
          cd /home/erjiangao/services/tutor-selection-tool/
          docker-compose up -d
          [ $(docker images -f dangling=true docker.pkg.github.com/erjiangao/tutor-selection-tool-vue/tutor-selection-tool-vue:latest -q) ] && \
           docker rmi $(docker images -f dangling=true docker.pkg.github.com/erjiangao/tutor-selection-tool-vue/tutor-selection-tool-vue:latest -q)
